// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZJ6P6jeefjJ7rvYaQ_yGhoPaO6IxOwI',
    appId: '1:850662968743:web:1b2fc41ea0f2f92056fa82',
    messagingSenderId: '850662968743',
    projectId: 'dthlmschat',
    authDomain: 'dthlmschat.firebaseapp.com',
    storageBucket: 'dthlmschat.appspot.com',
    measurementId: 'G-V1B3S42MCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHFsExzptuNmaoQ1fO6NifD0NhAVH8iU',
    appId: '1:850662968743:android:46fa221de66f8c2e56fa82',
    messagingSenderId: '850662968743',
    projectId: 'dthlmschat',
    storageBucket: 'dthlmschat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr1H7Pl4rqoY3g5sCU9WZ83b2081we6x8',
    appId: '1:850662968743:ios:dd6899bbad253b9d56fa82',
    messagingSenderId: '850662968743',
    projectId: 'dthlmschat',
    storageBucket: 'dthlmschat.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr1H7Pl4rqoY3g5sCU9WZ83b2081we6x8',
    appId: '1:850662968743:ios:dd6899bbad253b9d56fa82',
    messagingSenderId: '850662968743',
    projectId: 'dthlmschat',
    storageBucket: 'dthlmschat.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnZJ6P6jeefjJ7rvYaQ_yGhoPaO6IxOwI',
    appId: '1:850662968743:web:05c9e1d5fccb88c456fa82',
    messagingSenderId: '850662968743',
    projectId: 'dthlmschat',
    authDomain: 'dthlmschat.firebaseapp.com',
    storageBucket: 'dthlmschat.appspot.com',
    measurementId: 'G-4NWJGPCLN0',
  );
}
